<a href="https://colab.research.google.com/github/fahmisyuhada/Klasifikasi-Diabetes-dengan-C.45/blob/main/KLASIFIKASI_DIABETES_DENGAN_ALGORITAM_C_45.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("heart_attack_prediction_dataset.csv", sep=",")

In [3]:
dataset

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,MSV9918,60,Male,121,94/76,61,1,1,1,0,...,10.806373,235420,19.655895,67,7,7,Thailand,Asia,Northern Hemisphere,0
8759,QSV6764,28,Female,120,157/102,73,1,0,0,1,...,3.833038,217881,23.993866,617,4,9,Canada,North America,Northern Hemisphere,0
8760,XKA5925,47,Male,250,161/75,105,0,1,1,1,...,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere,1
8761,EPE6801,36,Male,178,119/67,60,1,0,1,0,...,0.029104,209943,27.294020,114,2,8,Brazil,South America,Southern Hemisphere,0
8762,ZWN9666,25,Female,356,138/67,75,1,1,0,0,...,9.005234,247338,32.914151,180,7,4,United Kingdom,Europe,Northern Hemisphere,1

In [4]:
dataset.head()

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Patient ID                       8763 non-null   object
 1   Age                              8763 non-null   int64
 2   Sex                              8763 non-null   object
 3   Cholesterol                      8763 non-null   int64
 4   Blood Pressure                   8763 non-null   object
 5   Heart Rate                       8763 non-null   int64
 6   Diabetes                         8763 non-null   int64
 7   Family History                   8763 non-null   int64
 8   Smoking                          8763 non-null   int64
 9   Obesity                          8763 non-null   int64
 10  Alcohol Consumption              8763 non-null   int64
 11  Exercise Hours Per Week          8763 non-null   float64
 12  Diet                             8763 non-null   object
 13  Previous Heart Problems          8763 non-null   int64
 14  Medication Use                   8763 non-null   int64
 15  Stress Level                     8763 non-null   int64
 16  Sedentary Hours Per Day          8763 non-null   float64
 17  Income                           8763 non-null   int64
 18  BMI                              8763 non-null   float64
 19  Triglycerides                    8763 non-null   int64
 20  Physical Activity Days Per Week  8763 non-null   int64
 21  Sleep Hours Per Day              8763 non-null   int64
 22  Country                          8763 non-null   object
 23  Continent                        8763 non-null   object
 24  Hemisphere                       8763 non-null   object
 25  Heart Attack Risk                8763 non-null   int64
dtypes: float64(3), int64(16), object(7)
memory usage: 1.7+ MB

In [7]:
from sklearn.preprocessing import LabelEncoder

In [10]:
enc = LabelEncoder()

In [13]:
dataset["Sex"] = enc.fit_transform(dataset['Sex'].values)
dataset["Blood Pressure"] = enc.fit_transform(dataset['Blood Pressure'].values)

In [14]:
dataset.head()

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,1,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,1,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,0,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,1,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,1,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0

In [18]:

dataset["Diet"] = enc.fit_transform(dataset['Diet'].values)
dataset["Country"] = enc.fit_transform(dataset['Country'].values)
dataset["Continent"] = enc.fit_transform(dataset['Continent'].values)
dataset["Hemisphere"] = enc.fit_transform(dataset['Hemisphere'].values)

In [20]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Patient ID                       8763 non-null   object
 1   Age                              8763 non-null   int64
 2   Sex                              8763 non-null   int64
 3   Cholesterol                      8763 non-null   int64
 4   Blood Pressure                   8763 non-null   int64
 5   Heart Rate                       8763 non-null   int64
 6   Diabetes                         8763 non-null   int64
 7   Family History                   8763 non-null   int64
 8   Smoking                          8763 non-null   int64
 9   Obesity                          8763 non-null   int64
 10  Alcohol Consumption              8763 non-null   int64
 11  Exercise Hours Per Week          8763 non-null   float64
 12  Diet                             8763 non-null   int64
 13  Previous Heart Problems          8763 non-null   int64
 14  Medication Use                   8763 non-null   int64
 15  Stress Level                     8763 non-null   int64
 16  Sedentary Hours Per Day          8763 non-null   float64
 17  Income                           8763 non-null   int64
 18  BMI                              8763 non-null   float64
 19  Triglycerides                    8763 non-null   int64
 20  Physical Activity Days Per Week  8763 non-null   int64
 21  Sleep Hours Per Day              8763 non-null   int64
 22  Country                          8763 non-null   int64
 23  Continent                        8763 non-null   int64
 24  Hemisphere                       8763 non-null   int64
 25  Heart Attack Risk                8763 non-null   int64
dtypes: float64(3), int64(22), object(1)
memory usage: 1.7+ MB

In [21]:
atr_data = dataset.drop(columns = ['Diabetes', 'Patient ID'])

In [22]:
atr_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Age                              8763 non-null   int64
 1   Sex                              8763 non-null   int64
 2   Cholesterol                      8763 non-null   int64
 3   Blood Pressure                   8763 non-null   int64
 4   Heart Rate                       8763 non-null   int64
 5   Family History                   8763 non-null   int64
 6   Smoking                          8763 non-null   int64
 7   Obesity                          8763 non-null   int64
 8   Alcohol Consumption              8763 non-null   int64
 9   Exercise Hours Per Week          8763 non-null   float64
 10  Diet                             8763 non-null   int64
 11  Previous Heart Problems          8763 non-null   int64
 12  Medication Use                   8763 non-null   int64
 13  Stress Level                     8763 non-null   int64
 14  Sedentary Hours Per Day          8763 non-null   float64
 15  Income                           8763 non-null   int64
 16  BMI                              8763 non-null   float64
 17  Triglycerides                    8763 non-null   int64
 18  Physical Activity Days Per Week  8763 non-null   int64
 19  Sleep Hours Per Day              8763 non-null   int64
 20  Country                          8763 non-null   int64
 21  Continent                        8763 non-null   int64
 22  Hemisphere                       8763 non-null   int64
 23  Heart Attack Risk                8763 non-null   int64
dtypes: float64(3), int64(21)
memory usage: 1.6 MB

In [24]:
tar_data = dataset['Diabetes']
tar_data

0       0
1       1
2       1
3       1
4       1
       ..
8758    1
8759    1
8760    0
8761    1
8762    1
Name: Diabetes, Length: 8763, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier

In [26]:
xtrain, xtest, ytrain, ytest = train_test_split(atr_data, tar_data, test_size=0.2, random_state=1)

In [27]:
tree_dataset = DecisionTreeClassifier(random_state=1)

In [29]:
tree_dataset.fit(xtrain,ytrain)

DecisionTreeClassifier(random_state=1)

In [31]:
y_predict = tree_dataset.predict(xtest)

cm = confusion_matrix(ytest, y_predict)
print("Confusion Matrix")
print(cm)

akurasi = classification_report(ytest, y_predict)
print("Tingkat akurasi metode C5.5 : ")
print("Akurasi : ", akurasi)
akurasi = accuracy_score(ytest, y_predict)
print("tingkat akurasi : %d persen"%(akurasi*100))

Confusion Matrix
[[213 424]
 [418 698]]
Tingkat akurasi metode C5.5 :
Akurasi :                precision    recall  f1-score   support

           0       0.34      0.33      0.34       637
           1       0.62      0.63      0.62      1116

    accuracy                           0.52      1753
   macro avg       0.48      0.48      0.48      1753
weighted avg       0.52      0.52      0.52      1753

tingkat akurasi : 51 persen